### ISSUE TITLE
user can vote only after login and vote once

### ISSUE THREAD

**Issue by tommyshieh** [eecs394-spr15/Click#7]
user can only vote after login

**Comment by esun9064** [comment]
User can upvote twice before message appears saying they can no longer vote.

**Comment by tommyshieh** [comment]
what do you mean vote twice?!  Like when original vote is 60, user can down vote to 59. But he suddenly think it is good, so the can upvote to 61. Is it right?

**Comment by esun9064** [comment]
If Vote is 60. You can downvote to 58 before it tells you you can not vote
anymore

**Comment by tommyshieh** [comment]
Got, it sometimes happen, let me fix it!

**Comment by esun9064** [comment]
Okay cool
